import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })
/*        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:title" content="Your Title"></meta>
        <meta name="twitter:title" content="Your Title"></meta>
        
        <meta name="description" content="YouTube is 15 years old. Here's a timeline of how YouTube was founded, its rise to video behemoth, and its biggest controversies along way"></meta>
        <meta property="og:description" content="YouTube is 15 years old. Here's a timeline of how YouTube was founded, its rise to video behemoth, and its biggest controversies along way"></meta>
        <meta name="twitter:description" content="YouTube is 15 years old. Here's a timeline of how YouTube was founded, its rise to video behemoth, and its biggest controversies along way"></meta>
        
        <meta property="og:image" content="https://www.businessinsider.in/thumb/msid-76111673,width-700,height-525,imgsize-308344/YouTube-is-15-years-old-Heres-a-timeline-of-how-YouTube-was-founded-its-rise-to-video-behemoth-and-its-biggest-controversies-along-way.jpg">
        </meta>
        <meta name="twitter:image" content="https://www.businessinsider.in/thumb/msid-76111673,width-700,height-525,imgsize-308344/YouTube-is-15-years-old-Heres-a-timeline-of-how-YouTube-was-founded-its-rise-to-video-behemoth-and-its-biggest-controversies-along-way.jpg">
        </meta>
        <link rel="icon" href="/favicon.ico" /> */
        /*
              <meta content="Business Insider" property="og:site_name"></meta>
        <meta property="og:title" content="YouTube is 15 years old. Here's a timeline of how YouTube was founded, its rise to video behemoth, and its biggest controversies along way">
        </meta>
        <meta property="og:url" content="https://www.businessinsider.in/tech/news/youtube-is-15-years-old-hereaposs-a-timeline-of-how-youtube-was-founded-its-rise-to-video-behemoth-and-its-biggest-controversies-along-way/slidelist/76111673.cms">
        </meta>
        <meta property="og:description" content="YouTube CEO Susan Wojcicki.GettyYouTube has more than 2 billion monthly users visiting the video-sharing platform for their favorite vlogs, music videos, sports highlights, and more.It's been 15 years since YouTube's website launched to the public in May 2005.YouTube was founded earlier that year by three early PayPal employees. Since then, it's become the most popular free video-sharing platform in the world.Take a look at the history of YouTube, from its start as a failed video-dating website to a powerhouse platform that's launched a new generation of money-making YouTubers and influencers.In its 15-year history, YouTube has become the undisputed king of online video.It has over 2 billion monthly users who watch hundreds of hundreds of millions of hours of content every single day. But many people don't know how YouTube got its start.The company rose like a rocket ship after its founding in 2005, and was bought by Google 18 months later. Under Google, YouTube went from being a repository of amateur video to a powerhouse of original content, not to mention a launching pad for its own new brand of superstar, like PewDiePie and the Smosh Brothers.Here is how YouTube got its explosive start, and maintained that momentum to become the biggest force in online video.Read the original article on Business Insider">
          </meta>
        <meta property="og:image" content="https://www.businessinsider.in/photo/76111673/YouTube-is-15-years-old-Heres-a-timeline-of-how-YouTube-was-founded-its-rise-to-video-behemoth-and-its-biggest-controversies-along-way.jpg">
        </meta>
        <meta content="biindia" property="snapchat">
          </meta>
          <meta property="snapchat:sticker" content="https://www.businessinsider.in/thumb/msid-76111673,width-720,height-310/YouTube-is-15-years-old-Heres-a-timeline-of-how-YouTube-was-founded-its-rise-to-video-behemoth-and-its-biggest-controversies-along-way.jpg">
            </meta>
            <meta name="twitter:card" value="summary_large_image">
            </meta>
            <meta name="twitter:site" value="@BiIndia">
              </meta>
              <meta name="twitter:url" content="https://www.businessinsider.in/tech/news/youtube-is-15-years-old-hereaposs-a-timeline-of-how-youtube-was-founded-its-rise-to-video-behemoth-and-its-biggest-controversies-along-way/slidelist/76111673.cms">
                </meta>
                  <meta name="twitter:title" content="YouTube is 15 years old. Here's a timeline of how YouTube was founded, its rise to video behemoth, and its biggest controversies along way">
                  </meta> 
                    <meta name="twitter:description" content="YouTube CEO Susan Wojcicki.GettyYouTube has more than 2 billion monthly users visiting the video-sharing platform for their favorite vlogs, music videos, sports highlights, and more.It's been 15 years since YouTube's website launched to the public in May 2005.YouTube was founded earlier that year by three early PayPal employees. Since then, it's become the most popular free video-sharing platform in the world.Take a look at the history of YouTube, from its start as a failed video-dating website to a powerhouse platform that's launched a new generation of money-making YouTubers and influencers.In its 15-year history, YouTube has become the undisputed king of online video.It has over 2 billion monthly users who watch hundreds of hundreds of millions of hours of content every single day. But many people don't know how YouTube got its start.The company rose like a rocket ship after its founding in 2005, and was bought by Google 18 months later. Under Google, YouTube went from being a repository of amateur video to a powerhouse of original content, not to mention a launching pad for its own new brand of superstar, like PewDiePie and the Smosh Brothers.Here is how YouTube got its explosive start, and maintained that momentum to become the biggest force in online video.Read the original article on Business Insider">
                    </meta>
                    <meta name="twitter:image" content="https://www.businessinsider.in/photo/76111673/YouTube-is-15-years-old-Heres-a-timeline-of-how-YouTube-was-founded-its-rise-to-video-behemoth-and-its-biggest-controversies-along-way.jpg">
                       </meta> */
export default function Home() {
  return (
    <>
      <Head>
    <title>Google</title>
    <meta name="title" content="Google"></meta>
    <meta name="description" content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for.">
    </meta>
    <meta property="og:type" content="website">
    </meta>
    <meta property="og:url" content="https://www.google.com/">
    </meta>
    <meta property="og:title" content="Google">
    </meta>
    <meta property="og:description" content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for.">
    </meta>
    <meta property="og:image" content="https://www.businessinsider.in/thumb/msid-76111673,width-700,height-525,imgsize-308344/YouTube-is-15-years-old-Heres-a-timeline-of-how-YouTube-was-founded-its-rise-to-video-behemoth-and-its-biggest-controversies-along-way.jpg">
    </meta>

    <meta property="twitter:card" content="summary_large_image">
    </meta>
    <meta property="twitter:url" content="https://www.google.com/">
    </meta>
    <meta property="twitter:title" content="Google">
    </meta>
    <meta property="twitter:description" content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for.">
    </meta>
    <meta property="twitter:image" content="https://www.businessinsider.in/thumb/msid-76111673,width-700,height-525,imgsize-308344/YouTube-is-15-years-old-Heres-a-timeline-of-how-YouTube-was-founded-its-rise-to-video-behemoth-and-its-biggest-controversies-along-way.jpg">
    </meta>


      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
